nodeEnv: "k8s"
appName: "fleet-node-1"

# fleet node config
apiKey: "83jklolTL!-test-1"
imageURL: "069870223720.dkr.ecr.eu-central-1.amazonaws.com/blxm/fleet-node"
accountDID: did:ethr:blxm-uat:0x5766D7546e056D8A9db6A580d54E0eEE7EA97ABb
backfillEnabled: "true"
swaggerBasePath: /fleet-node-1
defaultZone: STUTTGART
accessTokenExpirationSeconds: 300
accessTokenVcMaxFutureExpirationInSeconds: 10
resalePackageClaims: minAge18,driverLicense
backfillUpdateInterval: 20000
timestampExpirationInSeconds: 10
smartVin:
  enabled: false
  ownIdentity: Fleet1
  url:
    transferVehiclePossession: "http://fleet1.smartvin:8080/api/smartvin/vehicles/:vin/possession-transactions"
    consumeAgreement: "http://fleet1.smartvin:8080/api/smartvin/agreements/:agreementId/consumes"
    createAgreement: "http://fleet1.smartvin:8080/api/smartvin/agreements"
    getAgreement: "http://fleet1.smartvin:8080/api/smartvin/agreements/:agreementId/types/:type"
    getLiabilities: "http://fleet1.smartvin:8080/api/smartvin/liabilities"
    payLiability: "http://fleet1.smartvin:8080/api/smartvin/liabilities/:liabilityId/payments"
    issueCash: "http://fleet1.smartvin:8080/api/smartvin/cash"
    issueVehicle: "http://fleet1.smartvin:8080/api/smartvin/vehicles"

kycIssuers: "did:ethr:blxm-uat:0xf249B005C6E58ae9218af3423Ea1De06e93Ef6C1,did:ont:ALgcpQyKwudRKNnCZuUYjK47mqwZrzPNQG,did:web:doorman-pre-prod.wallet.eu.spherity.io:uuid:4f7d2251f7c34e829971a1ad8c41c6d2"
companyClaim: '''[{"@context":["https://www.w3.org/2018/credentials/v1"],"type":["VerifiableCredential","CompanyCredential"],"credentialSubject":{"id":"did:ethr:blxm-uat:0x5766D7546e056D8A9db6A580d54E0eEE7EA97ABb","company":true,"proofPurpose":"assertionMethod"},"issuer":"did:ethr:blxm-uat:0xf249B005C6E58ae9218af3423Ea1De06e93Ef6C1","issuanceDate":"2021-12-07T13:32:38.999Z","proof":{"type":"EcdsaSecp256k1RecoveryMethod2020","proofPurpose":"assertionMethod","verificationMethod":"did:ethr:blxm-uat:0xf249B005C6E58ae9218af3423Ea1De06e93Ef6C1#controller","created":"2021-12-07T13:32:38.988Z","proofValue":"0x8761f5a34cdece9aeefdeaed33d84991ed81c7cc0488a8c0301d41bd04e194274ac557bdbf03422aff420ef71dc1d5b2335fc2eb0e9142a976cfe746321dbf661b"}}]'''

# asset library config
ontId: did:ont:AYMEqbQ2Nz3YWJvrMaMS5xA5DhKrUvLeSm
ontPrivateKeyWIF: 
ontPublicKeyIndex: 1
ontNodeUrl: http://polaris1.ont.io:20334

web3Provider: ws://validator1-0.besu-validator1.besu:8546
chainId: 1000
networkName: blxm-uat
ipfsHost: local-ipfs.local-ipfs
ipfsPort: 5001
ipfsProtocol: http
ipfsBasePath: /api/v0
accountAddress: 0x5766D7546e056D8A9db6A580d54E0eEE7EA97ABb
accountPrivateKey: 
didRegistryAddress: 0x7b72a0943fea9c5B3DDA2b11a846882d548e6180
attestationRegistryAddress: 0xE4e989684cBc0E8B2DED99bCB45644C0Cf508bb1
ensAddress: 0xB6368320F27Bf65022618b667d22DA2d397EEeA4
currentAccountDidMethod: ethr

# connected endpoints
serviceCatalogAggregatorBaseUrl: https://uat.mobilityblockchainplatform.io/service-catalog-aggregator
serviceCatalogAggregatorApiKey: 

virtualCarWalletBaseUrl: https://uat.mobilityblockchainplatform.io/virtual-car-wallet

vehicleAuthorityBaseUrl: https://uat.mobilityblockchainplatform.io/vehicle-authority
vehicleAuthorityVehicleParentDomain: vin.bloxmove

fleetbackendBaseUrl: https://uat.mobilityblockchainplatform.io/fleet-backend
fleetBackendTenantId: 1

