nodeEnv: "k8s"
appName: "fleet-node-3"

# fleet node config
apiKey: "83jklolTL!-dev-3"
imageURL: "069870223720.dkr.ecr.eu-central-1.amazonaws.com/blxm/fleet-node"
accountDID: did:ethr:blxm-dev:0x72C64b506A87271B92be395B0AcFf4798716869D
backfillEnabled: "false"
swaggerBasePath: /fleet-node-3
defaultZone: STUTTGART
accessTokenExpirationSeconds: 300
accessTokenVcMaxFutureExpirationInSeconds: 10
resalePackageClaims: minAge18,driverLicense
backfillUpdateInterval: 20000
timestampExpirationInSeconds: 10
apiType: tomp
bloxmoveTompGatewayBaseUrl: https://dev.mobilityblockchainplatform.io/bloxmove-tomp-gateway
ownFleetNodeUrl: https://dev.mobilityblockchainplatform.io/fleet-node-3
kycIssuers: "did:ethr:blxm-dev:0x76fF7A937699D5Fdc02E70B23450deF8F321d3fB,did:ont:ALgcpQyKwudRKNnCZuUYjK47mqwZrzPNQG,did:web:doorman-pre-prod.wallet.eu.spherity.io:uuid:4f7d2251f7c34e829971a1ad8c41c6d2"

# asset library config
ontId: did:ont:AYMEqbQ2Nz3YWJvrMaMS5xA5DhKrUvLeSm
ontPrivateKeyWIF: 
ontPublicKeyIndex: 1
ontNodeUrl: http://polaris1.ont.io:20334

web3Provider: ws://validator1-0.besu-validator1.besu:8546
chainId: 1000
networkName: blxm-dev
ipfsHost: local-ipfs.local-ipfs
ipfsPort: 5001
ipfsProtocol: http
ipfsBasePath: /api/v0
accountAddress: 0x72C64b506A87271B92be395B0AcFf4798716869D
accountPrivateKey: 
didRegistryAddress: 0xc60784dE9cadec7d971175751ed3aE598AFd5CE2
attestationRegistryAddress: 0x706f11D9E8BD114723528D8FE975bAAC7c7C61e2
ensAddress: 0xEbCFd4584c6B56f342861039fE7cFfB87264B62c
currentAccountDidMethod: ethr

# connected endpoints
serviceCatalogAggregatorBaseUrl: https://dev.mobilityblockchainplatform.io/service-catalog-aggregator
serviceCatalogAggregatorApiKey:

virtualCarWalletBaseUrl: https://dev.mobilityblockchainplatform.io/virtual-car-wallet

vehicleAuthorityBaseUrl: https://dev.mobilityblockchainplatform.io/vehicle-authority
vehicleAuthorityVehicleParentDomain: vin.bloxmove